g++ -c Animal.cpp -w
g++ -c BodyBox.cpp -w
g++ -c Globals.cpp -w
g++ -c Inventory.cpp -w
g++ -c Item.cpp -w
g++ -c ItemStack.cpp -w
g++ -c Notification.cpp -w
g++ -c NotificationHandler.cpp -w
g++ -c WeaponBox.cpp -w
g++ -c main.cpp -w