g++ -c Animal.cpp
g++ -c BodyBox.cpp
g++ -c Globals.cpp
g++ -c Inventory.cpp
g++ -c Item.cpp
g++ -c ItemStack.cpp
g++ -c Notification.cpp
g++ -c NotificationHandler.cpp
g++ -c WeaponBox.cpp
g++ -c main.cpp